apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:compliance-history-api-recorder
rules:
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies/status
  verbs:
  - patch
