apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-addon-controller
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - governance-policy-addon-controller
        args:
        - controller
        image: policy-addon-image
        imagePullPolicy: Always
        env:
        - name: CONFIG_POLICY_CONTROLLER_IMAGE
          value: quay.io/open-cluster-management/config-policy-controller:latest
        - name: GOVERNANCE_POLICY_FRAMEWORK_ADDON_IMAGE
          value: quay.io/open-cluster-management/governance-policy-framework-addon:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
        volumeMounts:
        - name: serving-cert
          mountPath: /tmp
      serviceAccountName: governance-policy-addon-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - name: serving-cert
        emptyDir: {}
