# Copyright Contributors to the Open Cluster Management project

{{- if .Values.enabled }}
{{- if not (or (.Capabilities.APIVersions.Has "operator.open-cluster-management.io/v1/MultiClusterHub") (.Capabilities.APIVersions.Has "operator.open-cluster-management.io/v1beta1/MultiClusterHub")) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "policy.fullname" . }}-uninstall-ns
  labels:
    app: {{ template "policy.name" . }}-uninstall-ns
    chart: {{ template "policy.chart" . }}
    component: "governance"
    release: {{ .Release.Name }}
    controller: "operator"
    heritage: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "policy.fullname" . }}-uninstall-ns
      labels:
        app: {{ template "policy.name" . }}-uninstall-ns
        chart: {{ template "policy.chart" . }}
        component: "governance"
        release: {{ .Release.Name }}
        controller: "operator"
        heritage: {{ .Release.Service }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "policy.fullname" . }}
      containers:
      - name: uninstall-ns
        image: "{{ .Values.global.imageOverrides.governance_policy_spec_sync }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        command: ["uninstall-ns"]
        args: 
          - "--namespace={{ .Values.clusterNamespace }}"
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.global.imagePullSecret }}"
      {{- end }}
{{- end }}
{{- end }}
