# Copyright Contributors to the Open Cluster Management project

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "open-cluster-management:config-policy-controller-hub"
  namespace: "{{ .ClusterName }}"
roleRef:
  kind: ClusterRole
  name: open-cluster-management:config-policy-controller-hub
  apiGroup: rbac.authorization.k8s.io
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ .Group }}"
