# Copyright Contributors to the Open Cluster Management project

{{- if ne .Release.Namespace "open-cluster-management-agent-addon" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    addon.open-cluster-management.io/namespace: "true"
    addon.open-cluster-management.io/hosted-manifest-location: hosting
    {{- if and .Values.prometheus.enabled (eq .Values.kubernetesDistribution "OpenShift") }}
    openshift.io/cluster-monitoring: "true"
    {{- end }}
  {{- if eq (.Release.Namespace | trimPrefix "klusterlet-") .Values.clusterName }}
  annotations:
    "addon.open-cluster-management.io/deletion-orphan": ""
  {{- end }}
{{- end }}
