# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "controller.rolename" . }}
  {{- if eq .Values.installMode "Hosted" }}
  namespace: {{ .Release.Namespace }}
  {{- else }}
  namespace: {{ .Values.clusterName }}
  {{- end }}
  labels:
    app: {{ include "controller.fullname" . }}
    chart: {{ include "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    addon.open-cluster-management.io/hosted-manifest-location: hosting
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - policy-encryption-key
  resources:
  - secrets
  verbs:
  - delete
  - get
  - update
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  # template-sync requires ability to deal with all kinds of policies
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
