# Copyright Contributors to the Open Cluster Management project

{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ocm-{{ include "controller.fullname" . }}-metrics
  namespace: {{ .Values.prometheus.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "controller.fullname" . }}
    chart: {{ include "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    addon.open-cluster-management.io/hosted-manifest-location: hosting
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: metrics
    {{- if eq .Values.kubernetesDistribution "OpenShift" }}
    scheme: https
    {{- else }}
    scheme: http
    {{- end }}
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: {{ include "controller.fullname" . }}-metrics.{{ .Release.Namespace }}.svc
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "controller.fullname" . }}
      release: {{ .Release.Name }}
{{- end }}
