# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Pod
metadata:
  name: {{ include "controller.fullname" . }}-uninstall
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "controller.fullname" . }}-uninstall
    chart: {{ include "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    addon.open-cluster-management.io/hosted-manifest-location: hosting
  annotations:
    addon.open-cluster-management.io/addon-pre-delete: ""
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 0
  containers:
    - name: {{ .Chart.Name }}-uninstall
      image: "{{ .Values.global.imageOverrides.config_policy_controller }}"
      imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
      command: ["config-policy-controller"]
      args:
        - trigger-uninstall
        - --deployment-name={{ include "controller.fullname" . }}
        - --deployment-namespace={{ .Release.Namespace }}
        {{- if eq .Values.installMode "Hosted" }}
        - --policy-namespace={{ .Release.Namespace }}
        {{- else }}
        - --policy-namespace={{ .Values.clusterName }}
        - --additional-namespace=open-cluster-management-policies
        {{- end }}
        - --v={{ .Values.args.pkgLogLevel }}
      env:
        {{- if .Values.global.proxyConfig }}
        - name: HTTP_PROXY
          value: {{ .Values.global.proxyConfig.HTTP_PROXY }}
        - name: HTTPS_PROXY
          value: {{ .Values.global.proxyConfig.HTTPS_PROXY }}
        - name: NO_PROXY
          value: {{ .Values.global.proxyConfig.NO_PROXY }}
        {{- end }}
      resources: {{- toYaml .Values.resources | nindent 10 }}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
  {{- if .Values.global.imagePullSecret }}
  imagePullSecrets:
  - name: "{{ .Values.global.imagePullSecret }}"
  {{- end }}
  affinity: {{ toYaml .Values.affinity | nindent 8 }}
  {{- if hasKey .Values "tolerations" }}
  tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
  {{- end }}
  {{- if hasKey .Values.global "nodeSelector" }}
  nodeSelector: {{ toYaml .Values.global.nodeSelector | nindent 8 }}
  {{- end }}
  hostNetwork: false
  hostPID: false
  hostIPC: false
  serviceAccount: {{ include "controller.serviceAccountName" . }}
  securityContext:
    runAsNonRoot: true
    {{- if semverCompare ">= 1.25.0" (.Values.hostingClusterCapabilities.KubeVersion.Version | default .Capabilities.KubeVersion.Version) }}
    {{- /* newer OpenShift (4.12+) versions might require this to be explicitly set */}}
    {{- /* but not all older kubernetes versions can handle when it is set */}}
    seccompProfile:
      type: RuntimeDefault
    {{- end }}
