# Copyright Contributors to the Open Cluster Management project

{{- if eq .Values.installMode "Hosted" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocm:{{ include "controller.fullname" . }}
  labels:
    app: {{ include "controller.fullname" . }}
    chart: {{ include "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    addon.open-cluster-management.io/hosted-manifest-location: hosting
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - configurationpolicies.policy.open-cluster-management.io
  verbs:
  - get
  - list
  - watch
{{- end }}
