# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
{{- if eq .Values.installMode "Hosted" }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  creationTimestamp: null
  name: {{ include "controller.rolename" . }}
  {{- if eq .Values.installMode "Hosted" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: {{ include "controller.fullname" . }}
    chart: {{ include "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    addon.open-cluster-management.io/hosted-manifest-location: hosting
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if eq .Values.installMode "Hosted" }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "controller.rolename" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
